# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/RMX2185/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/realme/RMX2185

PRODUCT_COPY_FILES += \
    vendor/realme/RMX2185/proprietary/lib64/libaptXHD_encoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaptXHD_encoder.so \
    vendor/realme/RMX2185/proprietary/lib64/libaptX_encoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaptX_encoder.so \
    vendor/realme/RMX2185/proprietary/product/vendor_overlay/30/bin/hw/android.hardware.lights-service.mediatek:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/30/bin/hw/android.hardware.lights-service.mediatek \
    vendor/realme/RMX2185/proprietary/system_ext/apex/com.android.vndk.v30.apex.aa:$(TARGET_COPY_OUT_SYSTEM_EXT)/apex/com.android.vndk.v30.apex.aa \
    vendor/realme/RMX2185/proprietary/system_ext/apex/com.android.vndk.v30.apex.ab:$(TARGET_COPY_OUT_SYSTEM_EXT)/apex/com.android.vndk.v30.apex.ab \
    vendor/realme/RMX2185/proprietary/system_ext/apex/com.android.vndk.v30.apex.ac:$(TARGET_COPY_OUT_SYSTEM_EXT)/apex/com.android.vndk.v30.apex.ac \
    vendor/realme/RMX2185/proprietary/system_ext/etc/build.prop:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/build.prop \
    vendor/realme/RMX2185/proprietary/system_ext/etc/compatconfig/settings-platform-compat-config.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/compatconfig/settings-platform-compat-config.xml \
    vendor/realme/RMX2185/proprietary/system_ext/etc/default-permissions/default_permissions_com.android.wallpaper.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/default-permissions/default_permissions_com.android.wallpaper.xml \
    vendor/realme/RMX2185/proprietary/system_ext/etc/group:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/group \
    vendor/realme/RMX2185/proprietary/system_ext/etc/permissions/com.android.carrierconfig.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.carrierconfig.xml \
    vendor/realme/RMX2185/proprietary/system_ext/etc/permissions/com.android.emergency.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.emergency.xml \
    vendor/realme/RMX2185/proprietary/system_ext/etc/permissions/com.android.launcher3.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.launcher3.xml \
    vendor/realme/RMX2185/proprietary/system_ext/etc/permissions/com.android.provision.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.provision.xml \
    vendor/realme/RMX2185/proprietary/system_ext/etc/permissions/com.android.settings.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.settings.xml \
    vendor/realme/RMX2185/proprietary/system_ext/etc/permissions/com.android.storagemanager.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.storagemanager.xml \
    vendor/realme/RMX2185/proprietary/system_ext/etc/permissions/com.android.systemui.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.systemui.xml \
    vendor/realme/RMX2185/proprietary/system_ext/etc/permissions/privapp_whitelist_com.android.wallpaper.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/privapp_whitelist_com.android.wallpaper.xml

PRODUCT_PACKAGES += \
    PresencePolling \
    RcsService \
    WAPPushManager \
    CarrierConfig \
    EmergencyInfo \
    Launcher3QuickStep \
    Provision \
    QuickAccessWallet \
    Settings.apk \
    Settings.apk \
    StorageManager \
    SystemUI \
    ThemePicker \
    WallpaperCropper
