# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/RMX2185/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/realme/RMX2185

PRODUCT_COPY_FILES += \
    vendor/realme/RMX2185/proprietary/lib64/libaptXHD_encoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaptXHD_encoder.so \
    vendor/realme/RMX2185/proprietary/lib64/libaptX_encoder.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaptX_encoder.so \
    vendor/realme/RMX2185/proprietary/product/vendor_overlay/30/bin/hw/android.hardware.lights-service.mediatek:$(TARGET_COPY_OUT_PRODUCT)/vendor_overlay/30/bin/hw/android.hardware.lights-service.mediatek \
    vendor/realme/RMX2185/proprietary/system_ext/apex/com.android.vndk.v30.apex.aa:$(TARGET_COPY_OUT_SYSTEM_EXT)/apex/com.android.vndk.v30.apex.aa \
    vendor/realme/RMX2185/proprietary/system_ext/apex/com.android.vndk.v30.apex.ab:$(TARGET_COPY_OUT_SYSTEM_EXT)/apex/com.android.vndk.v30.apex.ab \
    vendor/realme/RMX2185/proprietary/system_ext/apex/com.android.vndk.v30.apex.ac:$(TARGET_COPY_OUT_SYSTEM_EXT)/apex/com.android.vndk.v30.apex.ac \
    vendor/realme/RMX2185/proprietary/system_ext/etc/build.prop:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/build.prop \
    vendor/realme/RMX2185/proprietary/system_ext/etc/compatconfig/settings-platform-compat-config.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/compatconfig/settings-platform-compat-config.xml \
    vendor/realme/RMX2185/proprietary/system_ext/etc/default-permissions/default_permissions_com.android.wallpaper.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/default-permissions/default_permissions_com.android.wallpaper.xml \
    vendor/realme/RMX2185/proprietary/system_ext/etc/group:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/group \
    vendor/realme/RMX2185/proprietary/system_ext/etc/permissions/androidx.window.extensions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/androidx.window.extensions.xml \
    vendor/realme/RMX2185/proprietary/system_ext/etc/permissions/com.android.carrierconfig.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.carrierconfig.xml \
    vendor/realme/RMX2185/proprietary/system_ext/etc/permissions/com.android.emergency.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.emergency.xml \
    vendor/realme/RMX2185/proprietary/system_ext/etc/permissions/com.android.provision.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.provision.xml \
    vendor/realme/RMX2185/proprietary/system_ext/etc/permissions/com.android.settings.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.settings.xml \
    vendor/realme/RMX2185/proprietary/system_ext/etc/permissions/com.android.storagemanager.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.storagemanager.xml \
    vendor/realme/RMX2185/proprietary/system_ext/etc/permissions/com.android.systemui.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.systemui.xml \
    vendor/realme/RMX2185/proprietary/system_ext/etc/permissions/privapp-permissions-oplus.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/privapp-permissions-oplus.xml \
    vendor/realme/RMX2185/proprietary/system_ext/etc/permissions/privapp_whitelist_com.android.wallpaper.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/privapp_whitelist_com.android.wallpaper.xml \
    vendor/realme/RMX2185/proprietary/system_ext/etc/sysconfig/hidden-api-whitelist-oplus.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/sysconfig/hidden-api-whitelist-oplus.xml \
    vendor/realme/RMX2185/proprietary/system_ext/lib64/liboplusgraphic.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/liboplusgraphic.so \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/Usb.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/Usb.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/VolumePanelSound.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/VolumePanelSound.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/WheelPicker.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/WheelPicker.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/camera_click.wav:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/camera_click.wav \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/charge.mp3:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/charge.mp3 \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/cover.mp3:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/cover.mp3 \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/critical_lowbattery.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/critical_lowbattery.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/delete.mp3:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/delete.mp3 \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/delete3.mp3:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/delete3.mp3 \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/dew.wav:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/dew.wav \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/ebook_open.mp3:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/ebook_open.mp3 \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/ebook_open2.mp3:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/ebook_open2.mp3 \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/ebook_page1.mp3:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/ebook_page1.mp3 \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/ebook_page3.mp3:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/ebook_page3.mp3 \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/error.mp3:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/error.mp3 \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/extended_effect_a.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/extended_effect_a.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/extended_effect_b.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/extended_effect_b.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/extended_effect_c.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/extended_effect_c.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/extended_effect_d.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/extended_effect_d.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/extended_effect_e.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/extended_effect_e.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/full_battery.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/full_battery.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/global_delete.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/global_delete.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/inefficacy.mp3:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/inefficacy.mp3 \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/lomo_click.mp3:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/lomo_click.mp3 \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/lowbattery.mp3:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/lowbattery.mp3 \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/machine.mp3:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/machine.mp3 \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/mechanism_down.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/mechanism_down.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/mechanism_up.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/mechanism_up.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/normal_lowbattery.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/normal_lowbattery.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/numberpicker_click.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/numberpicker_click.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/powerlow.mp3:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/powerlow.mp3 \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/poweroff.mp3:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/poweroff.mp3 \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/poweron.mp3:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/poweron.mp3 \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/pure_music_down.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/pure_music_down.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/pure_music_up.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/pure_music_up.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/slight_feedback.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/slight_feedback.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/sound_10s.mp3:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/sound_10s.mp3 \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/sound_5s.mp3:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/sound_5s.mp3 \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/technology_down.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/technology_down.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/technology_up.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/technology_up.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/touch.mp3:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/touch.mp3 \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/touch2.mp3:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/touch2.mp3 \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/touch3.mp3:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/touch3.mp3 \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/uncover.mp3:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/uncover.mp3 \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/warning3.mp3:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/warning3.mp3 \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/warrning.mp3:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/warrning.mp3 \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/weather_alarm_cloud.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/weather_alarm_cloud.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/weather_alarm_cloud2.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/weather_alarm_cloud2.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/weather_alarm_cloud3.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/weather_alarm_cloud3.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/weather_alarm_cloud4.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/weather_alarm_cloud4.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/weather_alarm_default.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/weather_alarm_default.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/weather_alarm_haze.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/weather_alarm_haze.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/weather_alarm_haze2.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/weather_alarm_haze2.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/weather_alarm_rain.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/weather_alarm_rain.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/weather_alarm_rain2.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/weather_alarm_rain2.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/weather_alarm_snow.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/weather_alarm_snow.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/weather_alarm_snow2.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/weather_alarm_snow2.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/weather_alarm_sun.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/weather_alarm_sun.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/weather_alarm_sun2.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/weather_alarm_sun2.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/weather_alarm_sun3.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/weather_alarm_sun3.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/weather_alarm_sun4.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/weather_alarm_sun4.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/weather_alarm_thunderstorm.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/weather_alarm_thunderstorm.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/weather_alarm_thunderstorm2.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/weather_alarm_thunderstorm2.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/weather_alarm_thunderstorm3.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/weather_alarm_thunderstorm3.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/weather_alarm_wind.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/weather_alarm_wind.ogg \
    vendor/realme/RMX2185/proprietary/system_ext/media/audio/ui/weather_alarm_wind2.ogg:$(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/weather_alarm_wind2.ogg

PRODUCT_PACKAGES += \
    Athena \
    AthenaConfigPlugin \
    PresencePolling \
    RcsService \
    RomUpdate \
    WAPPushManager \
    CarrierConfig \
    DeepThinker \
    EmergencyInfo \
    OplusAppPlatform \
    OplusExSystemService \
    OplusLauncher \
    OplusSettingsIntelligence \
    Provision \
    QuickAccessWallet \
    Settings.apk \
    Settings.apk \
    StorageManager \
    SystemUI \
    ThemePicker \
    WallpaperCropper \
    WirelessSettings \
    androidx.window.extensions
